/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author nikollace
 */
public class FrmLogin extends javax.swing.JFrame{

    /**
     * Creates new form frmPrijavljivanjeStomatologa
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        cbShowPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(428, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        btnLogin.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLogin.setText("Prijava");
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnLogin);
        btnLogin.setBounds(300, 90, 90, 30);

        lblEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 30, 60, 20);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Unesite email...");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(120, 30, 260, 20);

        txtPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("Unesite sifru...");
        getContentPane().add(txtPassword);
        txtPassword.setBounds(120, 60, 260, 20);

        lblPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblPassword.setText("Sifra:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(10, 60, 100, 20);

        cbShowPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbShowPassword.setText("Prikazi sifru");
        getContentPane().add(cbShowPassword);
        cbShowPassword.setBounds(40, 90, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/loading.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(430, 350));
        jLabel1.setMinimumSize(new java.awt.Dimension(430, 350));
        jLabel1.setPreferredSize(new java.awt.Dimension(430, 350));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 270);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JCheckBox getCbShowPassword() {
        return cbShowPassword;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public JLabel getLblPassword() {
        return lblPassword;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    
    
    public void addCbPasswordMouseClikedListener(ActionListener actionListener) {
        cbShowPassword.addActionListener(actionListener);
    }
    
    public void loginAddActionListener(ActionListener actionListener) {
        btnLogin.addActionListener(actionListener);
    }

    public void addPasswordFocusListener(FocusAdapter focusAdapter) {
        txtPassword.addFocusListener(focusAdapter);
    }
}
