/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import rs.ac.bg.fon.ps.view.util.FormMode;

/**
 *
 * @author nikollace
 */
public class FrmMain extends javax.swing.JFrame {

    public FrmMain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        menuPatient = new javax.swing.JMenu();
        miPatientNew = new javax.swing.JMenuItem();
        miShowPatient = new javax.swing.JMenuItem();
        menuMedicalExamination = new javax.swing.JMenu();
        miScheduleMedicalExamination = new javax.swing.JMenuItem();
        miShowMedicalExamination = new javax.swing.JMenuItem();
        menuCurrentUser = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();
        miLogOut = new javax.swing.JMenuItem();
        menuAboutUs = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/dental-health-facts.jpg"))); // NOI18N

        menuMain.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        menuPatient.setText("Pacijent");
        menuPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        miPatientNew.setText("Novi pacijent");
        menuPatient.add(miPatientNew);

        miShowPatient.setText("Prikazi pacijente");
        menuPatient.add(miShowPatient);

        menuMain.add(menuPatient);

        menuMedicalExamination.setText("Pregled");
        menuMedicalExamination.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        miScheduleMedicalExamination.setText("Zakazi pregled");
        menuMedicalExamination.add(miScheduleMedicalExamination);

        miShowMedicalExamination.setText("Prikazi preglede");
        menuMedicalExamination.add(miShowMedicalExamination);

        menuMain.add(menuMedicalExamination);

        menuCurrentUser.setText("Ulogovani stomatolog");
        menuCurrentUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuMain.add(menuCurrentUser);

        menuLogOut.setText("                                                LogOut");

        miLogOut.setText("                                       LogOut");
        menuLogOut.add(miLogOut);

        menuMain.add(menuLogOut);

        menuAboutUs.setText("O nama");
        menuAboutUs.setFocusable(false);
        menuAboutUs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuMain.add(menuAboutUs);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public JMenu getMenuAboutUs() {
        return menuAboutUs;
    }

    public void setMenuAboutUs(JMenu menuAboutUs) {
        this.menuAboutUs = menuAboutUs;
    }

    public JMenuBar getMenuMain() {
        return menuMain;
    }

    public void setMenuMain(JMenuBar menuMain) {
        this.menuMain = menuMain;
    }

    public JMenu getMenuMedicalExamination() {
        return menuMedicalExamination;
    }

    public void setMenuMedicalExamination(JMenu menuMedicalExamination) {
        this.menuMedicalExamination = menuMedicalExamination;
    }

    public JMenu getMenuPatient() {
        return menuPatient;
    }

    public void setMenuPatient(JMenu menuPatient) {
        this.menuPatient = menuPatient;
    }

    public JMenuItem getMiPatientNew() {
        return miPatientNew;
    }

    public void setMiPatientNew(JMenuItem miPatientNew) {
        this.miPatientNew = miPatientNew;
    }

    public JMenuItem getMiScheduleMedicalExamination() {
        return miScheduleMedicalExamination;
    }

    public void setMiScheduleMedicalExamination(JMenuItem miScheduleMedicalExamination) {
        this.miScheduleMedicalExamination = miScheduleMedicalExamination;
    }

    public JMenuItem getMiShowMedicalExamination() {
        return miShowMedicalExamination;
    }

    public void setMiShowMedicalExamination(JMenuItem miShowMedicalExamination) {
        this.miShowMedicalExamination = miShowMedicalExamination;
    }

    public JMenuItem getMiShowPatient() {
        return miShowPatient;
    }

    public void setMiShowPatient(JMenuItem miShowPatient) {
        this.miShowPatient = miShowPatient;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAboutUs;
    private javax.swing.JMenu menuCurrentUser;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuMedicalExamination;
    private javax.swing.JMenu menuPatient;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JMenuItem miPatientNew;
    private javax.swing.JMenuItem miScheduleMedicalExamination;
    private javax.swing.JMenuItem miShowMedicalExamination;
    private javax.swing.JMenuItem miShowPatient;
    // End of variables declaration//GEN-END:variables

    public void miPatientNewAddActionListener(ActionListener actionListener) {
        miPatientNew.addActionListener(actionListener);
    }

    public void miPatientShowAllActionListener(ActionListener actionListener) {
        miShowPatient.addActionListener(actionListener);
    }
    
    public JMenu getMenuCurrentUser() {
        return menuCurrentUser;
    }

    public void miMedicalExaminationAddActionListener(ActionListener actionListener) {
        miScheduleMedicalExamination.addActionListener(actionListener);
    }
    
    public void miMedicalExaminationViewAllActionListener(ActionListener actionListener) {
        miShowMedicalExamination.addActionListener(actionListener);
    }
    
    public void miLogOutActionListener(ActionListener actionListener) {
        miLogOut.addActionListener(actionListener);
    }
}
