/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import de.wannawork.jcalendar.JCalendarComboBox;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author nikollace
 */
public class FrmMedicalExamination extends javax.swing.JFrame {

    /**
     * Creates new form FrmMedicalExamination
     */
    public FrmMedicalExamination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblTotalPrice = new javax.swing.JLabel();
        txtUkupnaCena = new javax.swing.JTextField();
        lblTotalDuration = new javax.swing.JLabel();
        txtUkupnoTrajanje = new javax.swing.JTextField();
        lblDentist = new javax.swing.JLabel();
        txtUlogovaniStomatolog = new javax.swing.JTextField();
        lblPatient = new javax.swing.JLabel();
        cbPacijenti = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkaPregleda = new javax.swing.JTable();
        btnDeleteItem = new javax.swing.JButton();
        pnlStavkaPregleda = new javax.swing.JPanel();
        lblType = new javax.swing.JLabel();
        txtNazivPregleda = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtCenaPregleda = new javax.swing.JTextField();
        txtTrajanjePregleda = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOpis = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlIzabraniPregled = new javax.swing.JPanel();
        lblTerminStart = new javax.swing.JLabel();
        lblTerminEnd = new javax.swing.JLabel();
        lblDateTermin = new javax.swing.JLabel();
        txtPocetakSati = new javax.swing.JTextField();
        txtKrajSati = new javax.swing.JTextField();
        btnSaveTermin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPocetakMinuti = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKrajMinuti = new javax.swing.JTextField();
        dateDatumTermina = new de.wannawork.jcalendar.JCalendarComboBox();
        btnScheduledTermins = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnEnableChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("ID:");

        lblTotalPrice.setText("Ukupna cena:");

        txtUkupnaCena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblTotalDuration.setText("Ukupno trajanje:");

        lblDentist.setText("Ulogovani stomatolog:");

        lblPatient.setText("Izaberite pacijenta:");

        tblStavkaPregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkaPregleda);

        btnDeleteItem.setText("Izbrisi stavku");

        pnlStavkaPregleda.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregled"));

        lblType.setText("Naziv:");

        lblPrice.setText("Cena:");

        txtCenaPregleda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblDuration.setText("Trajanje:");

        lblDescription.setText("Opis:");

        btnAddItem.setText("Dodaj stavku");

        taOpis.setColumns(20);
        taOpis.setRows(5);
        jScrollPane2.setViewportView(taOpis);

        javax.swing.GroupLayout pnlStavkaPregledaLayout = new javax.swing.GroupLayout(pnlStavkaPregleda);
        pnlStavkaPregleda.setLayout(pnlStavkaPregledaLayout);
        pnlStavkaPregledaLayout.setHorizontalGroup(
            pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStavkaPregledaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblDescription)
                        .addContainerGap())
                    .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                        .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPrice)
                                .addComponent(lblDuration))
                            .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                                .addComponent(lblType)
                                .addGap(15, 15, 15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                                .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCenaPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrajanjePregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNazivPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(198, 198, 198))
                            .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddItem)
                                .addContainerGap())))))
        );
        pnlStavkaPregledaLayout.setVerticalGroup(
            pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(txtNazivPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblPrice)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkaPregledaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCenaPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                        .addComponent(txtTrajanjePregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                        .addGroup(pnlStavkaPregledaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlStavkaPregledaLayout.createSequentialGroup()
                                .addComponent(lblDuration)
                                .addGap(25, 25, 25)
                                .addComponent(lblDescription)
                                .addGap(0, 99, Short.MAX_VALUE))
                            .addComponent(btnAddItem))
                        .addContainerGap())))
        );

        btnSave.setText("Sacuvaj");

        btnCancel.setText("Ponisti");

        pnlIzabraniPregled.setBorder(javax.swing.BorderFactory.createTitledBorder("Izaberite termin"));

        lblTerminStart.setText("Pocetak:");

        lblTerminEnd.setText("Kraj:");

        lblDateTermin.setText("Datum:");

        btnSaveTermin.setText("Sacuvaj");

        jLabel1.setText(":");

        jLabel2.setText(":");

        btnScheduledTermins.setText("Zakazani termini");

        javax.swing.GroupLayout pnlIzabraniPregledLayout = new javax.swing.GroupLayout(pnlIzabraniPregled);
        pnlIzabraniPregled.setLayout(pnlIzabraniPregledLayout);
        pnlIzabraniPregledLayout.setHorizontalGroup(
            pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTerminStart)
                            .addComponent(lblTerminEnd)
                            .addComponent(lblDateTermin))
                        .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                                        .addComponent(txtKrajSati, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKrajMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                                        .addComponent(txtPocetakSati, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPocetakMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnScheduledTermins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveTermin)))
                .addContainerGap())
        );
        pnlIzabraniPregledLayout.setVerticalGroup(
            pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzabraniPregledLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminStart)
                    .addComponent(txtPocetakSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtPocetakMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminEnd)
                    .addComponent(jLabel2)
                    .addComponent(txtKrajMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKrajSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateTermin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlIzabraniPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveTermin)
                    .addComponent(btnScheduledTermins))
                .addContainerGap())
        );

        btnDelete.setText("Obrisi pregled");

        btnEdit.setText("Izmeni pregled");

        btnEnableChanges.setText("Omoguci izmene");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalPrice)
                                            .addComponent(lblId))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUkupnaCena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDentist)
                                            .addComponent(lblTotalDuration)
                                            .addComponent(lblPatient))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUkupnoTrajanje, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(txtUlogovaniStomatolog, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(cbPacijenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlStavkaPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEnableChanges, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlIzabraniPregled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteItem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPrice)
                            .addComponent(txtUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalDuration)
                            .addComponent(txtUkupnoTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDentist)
                            .addComponent(txtUlogovaniStomatolog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatient)))
                    .addComponent(pnlIzabraniPregled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pnlStavkaPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnableChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(btnDelete))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnScheduledTermins() {
        return btnScheduledTermins;
    }

    public void setBtnScheduledTermins(JButton btnScheduledTermins) {
        this.btnScheduledTermins = btnScheduledTermins;
    }
    
    public JButton getBtnAddItem() {
        return btnAddItem;
    }

    public void setBtnAddItem(JButton btnAddItem) {
        this.btnAddItem = btnAddItem;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnDeleteItem() {
        return btnDeleteItem;
    }

    public void setBtnDeleteItem(JButton btnDeleteItem) {
        this.btnDeleteItem = btnDeleteItem;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public void setBtnEdit(JButton btnEdit) {
        this.btnEdit = btnEdit;
    }

    public JButton getBtnEnableChanges() {
        return btnEnableChanges;
    }

    public void setBtnEnableChanges(JButton btnEnableChanges) {
        this.btnEnableChanges = btnEnableChanges;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnPonisti(JButton btnPonisti) {
        this.btnCancel = btnPonisti;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(JButton btnSave) {
        this.btnSave = btnSave;
    }

    public JButton getBtnSaveTermin() {
        return btnSaveTermin;
    }

    public void setBtnSaveTermin(JButton btnSaveTermin) {
        this.btnSaveTermin = btnSaveTermin;
    }

    public JComboBox<Object> getCbPacijenti() {
        return cbPacijenti;
    }

    public void setCbPacijenti(JComboBox<Object> cbPacijenti) {
        this.cbPacijenti = cbPacijenti;
    }

    public JCalendarComboBox getDateDatumTermina() {
        return dateDatumTermina;
    }

    public void setDateDatumTermina(JCalendarComboBox dateDatumTermina) {
        this.dateDatumTermina = dateDatumTermina;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLblDateTermin() {
        return lblDateTermin;
    }

    public void setLblDateTermin(JLabel lblDateTermin) {
        this.lblDateTermin = lblDateTermin;
    }

    public JLabel getLblDentist() {
        return lblDentist;
    }

    public void setLblDentist(JLabel lblDentist) {
        this.lblDentist = lblDentist;
    }

    public JLabel getLblDescription() {
        return lblDescription;
    }

    public void setLblDescription(JLabel lblDescription) {
        this.lblDescription = lblDescription;
    }

    public JLabel getLblDuration() {
        return lblDuration;
    }

    public void setLblDuration(JLabel lblDuration) {
        this.lblDuration = lblDuration;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public JLabel getLblPatient() {
        return lblPatient;
    }

    public void setLblPatient(JLabel lblPatient) {
        this.lblPatient = lblPatient;
    }

    public JLabel getLblPrice() {
        return lblPrice;
    }

    public void setLblPrice(JLabel lblPrice) {
        this.lblPrice = lblPrice;
    }

    public JLabel getLblTerminEnd() {
        return lblTerminEnd;
    }

    public void setLblTerminEnd(JLabel lblTerminEnd) {
        this.lblTerminEnd = lblTerminEnd;
    }

    public JLabel getLblTerminStart() {
        return lblTerminStart;
    }

    public void setLblTerminStart(JLabel lblTerminStart) {
        this.lblTerminStart = lblTerminStart;
    }

    public JLabel getLblTotalDuration() {
        return lblTotalDuration;
    }

    public void setLblTotalDuration(JLabel lblTotalDuration) {
        this.lblTotalDuration = lblTotalDuration;
    }

    public JLabel getLblTotalPrice() {
        return lblTotalPrice;
    }

    public void setLblTotalPrice(JLabel lblTotalPrice) {
        this.lblTotalPrice = lblTotalPrice;
    }

    public JLabel getLblType() {
        return lblType;
    }

    public void setLblType(JLabel lblType) {
        this.lblType = lblType;
    }

    public JPanel getPnlIzabraniPregled() {
        return pnlIzabraniPregled;
    }

    public void setPnlIzabraniPregled(JPanel pnlIzabraniPregled) {
        this.pnlIzabraniPregled = pnlIzabraniPregled;
    }

    public JPanel getPnlStavkaPregleda() {
        return pnlStavkaPregleda;
    }

    public void setPnlStavkaPregleda(JPanel pnlStavkaPregleda) {
        this.pnlStavkaPregleda = pnlStavkaPregleda;
    }

    public JTextArea getTaOpis() {
        return taOpis;
    }

    public void setTaOpis(JTextArea taOpis) {
        this.taOpis = taOpis;
    }

    public JTable getTblStavkaPregleda() {
        return tblStavkaPregleda;
    }

    public void setTblStavkaPregleda(JTable tblStavkaPregleda) {
        this.tblStavkaPregleda = tblStavkaPregleda;
    }

    public JTextField getTxtCenaPregleda() {
        return txtCenaPregleda;
    }

    public void setTxtCenaPregleda(JTextField txtCenaPregleda) {
        this.txtCenaPregleda = txtCenaPregleda;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtKrajMinuti() {
        return txtKrajMinuti;
    }

    public void setTxtKrajMinuti(JTextField txtKrajMinuti) {
        this.txtKrajMinuti = txtKrajMinuti;
    }

    public JTextField getTxtKrajSati() {
        return txtKrajSati;
    }

    public void setTxtKrajSati(JTextField txtKrajSati) {
        this.txtKrajSati = txtKrajSati;
    }

    public JTextField getTxtNazivPregleda() {
        return txtNazivPregleda;
    }

    public void setTxtNazivPregleda(JTextField txtNazivPregleda) {
        this.txtNazivPregleda = txtNazivPregleda;
    }

    public JTextField getTxtPocetakMinuti() {
        return txtPocetakMinuti;
    }

    public void setTxtPocetakMinuti(JTextField txtPocetakMinuti) {
        this.txtPocetakMinuti = txtPocetakMinuti;
    }

    public JTextField getTxtPocetakSati() {
        return txtPocetakSati;
    }

    public void setTxtPocetakSati(JTextField txtPocetakSati) {
        this.txtPocetakSati = txtPocetakSati;
    }

    public JTextField getTxtTrajanjePregleda() {
        return txtTrajanjePregleda;
    }

    public void setTxtTrajanjePregleda(JTextField txtTrajanjePregleda) {
        this.txtTrajanjePregleda = txtTrajanjePregleda;
    }

    public JTextField getTxtUkupnaCena() {
        return txtUkupnaCena;
    }

    public void setTxtUkupnaCena(JTextField txtUkupnaCena) {
        this.txtUkupnaCena = txtUkupnaCena;
    }

    public JTextField getTxtUkupnoTrajanje() {
        return txtUkupnoTrajanje;
    }

    public void setTxtUkupnoTrajanje(JTextField txtUkupnoTrajanje) {
        this.txtUkupnoTrajanje = txtUkupnoTrajanje;
    }

    public JTextField getTxtUlogovaniStomatolog() {
        return txtUlogovaniStomatolog;
    }

    public void setTxtUlogovaniStomatolog(JTextField txtUlogovaniStomatolog) {
        this.txtUlogovaniStomatolog = txtUlogovaniStomatolog;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnableChanges;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveTermin;
    private javax.swing.JButton btnScheduledTermins;
    private javax.swing.JComboBox<Object> cbPacijenti;
    private de.wannawork.jcalendar.JCalendarComboBox dateDatumTermina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDateTermin;
    private javax.swing.JLabel lblDentist;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTerminEnd;
    private javax.swing.JLabel lblTerminStart;
    private javax.swing.JLabel lblTotalDuration;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnlIzabraniPregled;
    private javax.swing.JPanel pnlStavkaPregleda;
    private javax.swing.JTextArea taOpis;
    private javax.swing.JTable tblStavkaPregleda;
    private javax.swing.JTextField txtCenaPregleda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKrajMinuti;
    private javax.swing.JTextField txtKrajSati;
    private javax.swing.JTextField txtNazivPregleda;
    private javax.swing.JTextField txtPocetakMinuti;
    private javax.swing.JTextField txtPocetakSati;
    private javax.swing.JTextField txtTrajanjePregleda;
    private javax.swing.JTextField txtUkupnaCena;
    private javax.swing.JTextField txtUkupnoTrajanje;
    private javax.swing.JTextField txtUlogovaniStomatolog;
    // End of variables declaration//GEN-END:variables


    public void addSacuvajTerminActionListener(ActionListener actionListener) {
        btnSaveTermin.addActionListener(actionListener);
    }

    public void addDodajStavkuPregledaActionListener(ActionListener actionListener) {
        btnAddItem.addActionListener(actionListener);
    }

    public void addIzbrisiStavkuPregledaActionListener(ActionListener actionListener) {
        btnDeleteItem.addActionListener(actionListener);
    }

    public void addPonistiActionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }

    public void addSaveMedicalExaminationActionListener(ActionListener actionListener) {
        btnSave.addActionListener(actionListener);
    }

    public void addBtnEnableChangesActionListener(ActionListener actionListener) {
        btnEnableChanges.addActionListener(actionListener);
    }

    public void addEditBtnActionListener(ActionListener actionListener) {
        btnEdit.addActionListener(actionListener);
    }

    public void addDeleteBtnActionListener(ActionListener actionListener) {
        btnDelete.addActionListener(actionListener);
    }
    
    public void addScheduledTerminsBtnActionListener(ActionListener actionListener) {
        btnScheduledTermins.addActionListener(actionListener);
    }
}

