/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author nikollace
 */
public class FrmStart extends javax.swing.JDialog {

    /**
     * Creates new form FrmStart
     */
    public FrmStart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbEnglish = new javax.swing.JRadioButton();
        rbSerbian = new javax.swing.JRadioButton();
        lblAccount = new javax.swing.JLabel();
        lblAccount2 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblLogIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Account options"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose language"));

        rbEnglish.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbEnglish.setText("English");
        jPanel1.add(rbEnglish);

        rbSerbian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbSerbian.setText("Serbian");
        jPanel1.add(rbSerbian);

        lblAccount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAccount.setText("You already have account?");

        lblAccount2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAccount2.setText("You don't have account? ");

        lblRegister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 51));
        lblRegister.setText("Register now!");

        lblLogIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 153, 51));
        lblLogIn.setText("Log In");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccount2)
                            .addComponent(lblAccount))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegister))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccount2)
                    .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccount)
                    .addComponent(lblLogIn))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JLabel getLblLogIn() {
        return lblLogIn;
    }

    public void setLblLogIn(JLabel lblLogIn) {
        this.lblLogIn = lblLogIn;
    }

    public JLabel getLblRegister() {
        return lblRegister;
    }

    public void setLblRegister(JLabel lblRegister) {
        this.lblRegister = lblRegister;
    }

    public JRadioButton getRbEnglish() {
        return rbEnglish;
    }

    public void setRbEnglish(JRadioButton rbEnglish) {
        this.rbEnglish = rbEnglish;
    }

    public JRadioButton getRbSerbian() {
        return rbSerbian;
    }

    public void setRbSerbian(JRadioButton rbSerbian) {
        this.rbSerbian = rbSerbian;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAccount2;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JRadioButton rbEnglish;
    private javax.swing.JRadioButton rbSerbian;
    // End of variables declaration//GEN-END:variables

    public void addRbSerbianLanguageActionListener(ActionListener actionListener) {
        rbSerbian.addActionListener(actionListener);
    }

    public void addRbEnglishLanguageActionListener(ActionListener actionListener) {
        rbEnglish.addActionListener(actionListener);
    }
}
