/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author nikollace
 */
public class FrmViewAllMedicalExamination extends javax.swing.JFrame {

    /**
     * Creates new form FrmViewAllMedicalExamination
     */
    public FrmViewAllMedicalExamination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicalExaminations = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtSearchValue = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        pnlEmptyValue = new javax.swing.JPanel();
        txtEmptyTable = new javax.swing.JTextField();
        lblTuzna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMedicalExaminations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMedicalExaminations);

        btnDetails.setText("Detalji");

        btnCancel.setText("Ponisti");

        txtSearchValue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblSearch.setText("Unesite vrednost po kojoj zelite da pronadjete pregled:");

        pnlEmptyValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtEmptyTable.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEmptyTable.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlEmptyValueLayout = new javax.swing.GroupLayout(pnlEmptyValue);
        pnlEmptyValue.setLayout(pnlEmptyValueLayout);
        pnlEmptyValueLayout.setHorizontalGroup(
            pnlEmptyValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmptyValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmptyTable)
                .addContainerGap())
        );
        pnlEmptyValueLayout.setVerticalGroup(
            pnlEmptyValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmptyValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmptyTable, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTuzna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/tuzan.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlEmptyValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblTuzna)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetails)
                    .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addGap(3, 3, 3)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEmptyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTuzna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBtnDetails() {
        return btnDetails;
    }

    public JTable getTblMedicalExaminations() {
        return tblMedicalExaminations;
    }

    public JTextField getTxtSearchValue() {
        return txtSearchValue;
    }

    public void setTxtSearchValue(JTextField txtSearchValue) {
        this.txtSearchValue = txtSearchValue;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JLabel getLblSearch() {
        return lblSearch;
    }

    public JPanel getPnlEmptyValue() {
        return pnlEmptyValue;
    }

    public void setPnlEmptyValue(JPanel pnlEmptyValue) {
        this.pnlEmptyValue = pnlEmptyValue;
    }

    public JTextField getTxtEmptyTable() {
        return txtEmptyTable;
    }

    public void setTxtEmptyTable(JTextField txtEmptyTable) {
        this.txtEmptyTable = txtEmptyTable;
    }

    public JLabel getLblTuzna() {
        return lblTuzna;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTuzna;
    private javax.swing.JPanel pnlEmptyValue;
    private javax.swing.JTable tblMedicalExaminations;
    private javax.swing.JTextField txtEmptyTable;
    private javax.swing.JTextField txtSearchValue;
    // End of variables declaration//GEN-END:variables

    public void btnDetailsAddAcionListener(ActionListener actionListener) {
        btnDetails.addActionListener(actionListener);
    }
    
    public void btnCancelAddAcionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }
}
